### ISSUE TITLE
Title bar bottom of the window?

### ISSUE THREAD

**Issue by Kleimo83** [numirias/paxmod#18]
Is it possible to add option to select the tab bar position? I am used to bottom of the window and would be nice to have the same option for this excellent extension also.

**Comment by Kleimo83** [comment]
I havent found working CSS but tabmixplus had this. Just the tab bar. Rest can be on the top.

**Comment by numirias** [comment]
I looked into this. The tabs, urlbar and everything you see in the header is inside one `#navigator-toolbox` element, so moving the tab row below the `#content-deck` (the site content) isn't just a matter of re-ordering elements (which could have been done with pure CSS).

Well, you can do something like this (paste it in the custom CSS field):

```css
#TabsToolbar {
    position: fixed !important;
    bottom: 0 !important;
    background: #ff0000 !important;
}
```

But since this extension works with multiple tab rows, that is, a dynamic tab row height, I don't see a straightforward way to shrink the content so that the tabs don't overlap.

So I'll close this for now. But feel free to come back to this if you have a suggestion how to implement that.
