### ISSUE TITLE
Inline title bar and collapses

### ISSUE THREAD

**Issue by Djagga-Djagga** [numirias/paxmod#19]
That what happened in MacOS after title bar update: http://prntscr.com/jlgx6p

And here are some snaps of other collapses an glitches:
- switched to fullscreen mode and back: https://prntscr.com/jl5ejh
- just happened after Nightly opened (pinned tabs appeared with huge space in between^ all other tabs moved to the right): 
https://prntscr.com/jkpa14
https://prntscr.com/jkpdso

tbh I'd personally prefer having 3buttons in top-left on MacOS, but not to waste additional space on titlebar as it is after update 2.4, so I reverted to 2.3 and it looks ok for me (http://prntscr.com/jlh332).

Regarding glitches - they disappeared after uninstalling your mod, reopening Nightly, and reinstalling mod again. SO maybe there is any chance that some kind of "reset mod" button can sort this out.

**Comment by Djagga-Djagga** [comment]
Ah, and as you can see on last screenshot - vertical separators on Bookmark toolbar are still appear invisible (but there are plenty of them)!

**Comment by numirias** [comment]
Thanks for all your help working on these bugs!

Unfortunately, the titlebar is platform-specific and since I only have Linux and Windows available right now, it's difficult for me to fix problems related to MacOS.

If you want to play around with titlebar-related CSS, paste this snippet in the "Custom CSS" box (best with v2.3 installed):

```css

#titlebar {
    visibility: var(--paxmod-titlebar-visibility);
    height: calc(var(--tab-min-height) + calc(var(--tab-min-height) - 26px)) !important;
    margin-bottom: calc(0px - var(--tab-min-height)) !important;
}

#main-window[sizemode="normal"] > #titlebar {
    display: var(--paxmod-titlebar-display);
}

#main-window[sizemode="maximized"] #titlebar {
    margin-bottom: calc(var(--paxmod-titlebar-margin) - var(--tab-min-height)) !important;
}

#titlebar:active #titlebar-content {
    margin-bottom: var(--tab-min-height) !important;
}

#TabsToolbar > .titlebar-placeholder {
    display: var(--paxmod-titlebar-display);
}

#titlebar-buttonbox {
    height: var(--tab-min-height) !important;
}

.titlebar-placeholder[type="post-tabs"],
.titlebar-placeholder[type="pre-tabs"] {
    width: 0 !important;
    border: none !important;
}
```
Maybe if you tweak some of those CSS rules you find a setting you like best.

I'll get back to this once I manage to run my own MacOS and debug the issues you're describing.

**Comment by numirias** [comment]
I made a new release with some reworked titlebar CSS code ([v2.5](https://github.com/numirias/paxmod/releases/tag/v2.5)). I'm not sure how much that fixed the problem for you, but it's about as good as I can do right now without additional help.

Thanks again for your reports and screenshots. And of course I'm open for any concrete code suggestions how to make the titlebar work better on MacOS.

**Comment by numirias** [comment]
> Ah, and as you can see on last screenshot - vertical separators on Bookmark toolbar are still appear invisible (but there are plenty of them)!

I could reproduce the problem on MacOS. However, as far as I can see the separators stay invisible even without Paxmod installed, so it appears to be an unrelated bug in Firefox.

**Comment by Djagga-Djagga** [comment]
I've tried 2.5. As for me, nothing really changed about titlebar.
That's not a big problem tbh, i tried switching on native mozilla titlebar and it looks okish for me (http://prntscr.com/jmenl3). Surely it takes some vertical space, but from other hand being able to see full window/tab name sometimes can be pretty handy.
I haven't tried your code for custom css, neither I'm capable of any coding at all, so I'm not a great assistant with this development. Just an ordinary user/consumer:)
Regarding separators on bookmarks titleber - true they remain invisible with all mods disabled. I thought that some css magic can solve this, coz for me it doesn't really seems right and convenient. But if it appears to be a problem - I'll be hapy with just multirowed tabs )))
Thanks for youк work - this is great addon. I just can suggest you to make it official!

**Comment by numirias** [comment]
@Djagga-Djagga Alright, I added a note to the readme about disabling the inline titlebar if it causes glitches. Will stop working on that specific problem for now.

> I thought that some css magic can solve this, coz for me it doesn't really seems right and convenient. 

Some CSS magic for you:

```css
#PersonalToolbar toolbarseparator {
    width: 1px !important;
    min-width: 1px !important;
    margin: 5px 4px !important;
    background: grey !important;
    -moz-appearance: none !important;
}
```
Just pasting this in the "Custom CSS" box should be enough to display the separators.
