### ISSUE TITLE
Setting to disable auto-hide of tab close buttons

### ISSUE THREAD

**Issue by markeast** [numirias/paxmod#30]
It would be lovely if the user had the option to have the close buttons on each tab appear always instead of only when hovered.

**Comment by numirias** [comment]
In the meantime, you can set this in the *Custom CSS* field:

```CSS
.tabbrowser-tab .tab-close-button {
    /* -moz-box is not accepted */
    display: -webkit-box !important;
}
```
